CREATE DATABASE SPMedGroup;
GO

USE SPMedGroup;
GO

CREATE TABLE tipoUsuario(
	IdTipoUsuario INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	nomeTipoUsuario VARCHAR (18) UNIQUE NOT NULL
);
GO

CREATE TABLE Especialidade(
	IdEspecialidade INT PRIMARY KEY IDENTITY NOT NULL,
	nomeEspecialidade VARCHAR (30) UNIQUE NOT NULL
);
GO

CREATE TABLE Situacao(
	IdSituacao INT PRIMARY KEY IDENTITY NOT NULL,
	nomeSituacao VARCHAR (15) UNIQUE NOT NULL
);
GO

CREATE TABLE Endereco(
	IdEndereco INT PRIMARY KEY IDENTITY NOT NULL,
	Rua VARCHAR(120) NOT NULL,
	Numero INT NOT NULL,
	Bairro VARCHAR(30) NOT NULL,
	Cidade VARCHAR(40) NOT NULL,
	Estado CHAR(2) NOT NULL,
	CEP CHAR(8) NOT NULL
);
GO

CREATE TABLE Clinica(
	IdClinica INT PRIMARY KEY IDENTITY NOT NULL,
	IdEndereco INT FOREIGN KEY REFERENCES Endereco(IdEndereco) NOT NULL,
	nomeClinica VARCHAR (20) UNIQUE NOT NULL, 
	CNPJ CHAR(20) UNIQUE NOT NULL,
	razaoSocial VARCHAR(20) UNIQUE NOT NULL,
	Telefone CHAR (15) UNIQUE NOT NULL
);
GO

CREATE TABLE Usuario(
	IdUsuario INT PRIMARY KEY IDENTITY NOT NULL,
	IdTipoUsuario INT FOREIGN KEY REFERENCES tipoUsuario(IdTipoUsuario) NOT NULL,
	nomeUsuario VARCHAR(20) UNIQUE NOT NULL,
	Email VARCHAR (256) UNIQUE NOT NULL,
	Senha VARCHAR (20) NOT NULL
);
GO

CREATE TABLE Medico(
	IdMedico INT PRIMARY KEY IDENTITY NOT NULL,
	IdUsuario INT FOREIGN KEY REFERENCES Usuario(IdUsuario) NOT NULL,
	IdClinica INT FOREIGN KEY REFERENCES Clinica(IdClinica) NOT NULL,
	IdEspecialidade INT FOREIGN KEY REFERENCES Especialidade(IdEspecialidade) NOT NULL,
	nomeMedico VARCHAR (20) NOT NULL,
	CRM CHAR(12) UNIQUE NOT NULL
);
GO

CREATE TABLE Paciente(
	idPaciente INT PRIMARY KEY IDENTITY NOT NULL,
	IdUsuario INT FOREIGN KEY REFERENCES Usuario(IdUsuario) NOT NULL,
	IdEndereco INT FOREIGN KEY REFERENCES Endereco(IdEndereco) NOT NULL,
	nomePaciente VARCHAR (20) NOT NULL,
	dataNascimento DATE NOT NULL,
	Telefone VARCHAR (20) UNIQUE,
	RG CHAR(9) UNIQUE NOT NULL,
	CPF CHAR(11) UNIQUE NOT NULL
);
GO

CREATE TABLE Consulta(
	IdConsulta INT PRIMARY KEY IDENTITY NOT NULL,
	IdPaciente INT FOREIGN KEY REFERENCES Paciente(IdPaciente) NOT NULL,
	IdMedico INT FOREIGN KEY REFERENCES Medico(IdMedico) NOT NULL,
	idSituacao INT FOREIGN KEY REFERENCES Situacao(IdSituacao) NOT NULL,
	dataConsulta DATETIME NOT NULL,
	DescricaoConsulta VARCHAR(400) DEFAULT(' ')
);
GO
